# Generated by Django 3.1.5 on 2021-04-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='messages',
            field=models.ManyToManyField(blank=True, to='messaging.Message'),
        ),
    ]
